### ISSUE TITLE
Validate dependencies

### ISSUE THREAD

**Issue by czyzby** [dragome/gdx-dragome#2]
`dragome-sdk` seems to depend on multiple libraries, which are unlikely do be needed by a plain HTML/JS application. [build.gradle](https://github.com/czyzby/gdx-dragome/blob/master/core/build.gradle) has to be validated - and corrected, if necessary - and should contain only the crucial libraries in its dependencies.

**Comment by fpetrola** [comment]
dragome is totally modular, you can discard all additional modules such as form-bindings, method-logger, guia, guia-web, callback-evictor, and also bytecode-js-compiler after you've generated js, and the application will be able to run in js and interact with browser DOM directly and execute native js.

**Comment by czyzby** [comment]
@fpetrola Gradle dependencies work pretty much like Maven dependencies, they just contain less boilerplate code. For example this dependency:

```
<dependency>
    <groupId>com.dragome</groupId>
    <artifactId>dragome-sdk</artifactId>
    <version>0.96-beta2</version>
</dependency>
```

Would require a single line in `build.gradle`: `compile 'com.dragome:dragome-sdk:0.96-beta2'`.

I'm still not sure which modules are crucial to run Dragome, so if we _can_ use multiple specific libraries instead of `dragome-sdk` (which seems to depend on modules which are not necessary), I think you should modify `build.gradle` yourself. If you think `dragome-sdk` is actually the way to go, this issue can be closed.

**Comment by czyzby** [comment]
For now, `js-jre`, `guia` and `web` seem to be the only required modules. I'm closing this, but if we can exclude even more, make sure to comment.
