### ISSUE TITLE
Preferences support

### ISSUE THREAD

**Issue by czyzby** [dragome/gdx-dragome#5]
Local storage can be used to store application's preferences. This requires native calls or support for local storage in Dragome.

**Comment by fpetrola** [comment]
There is a basic local storage support in bindings module: https://github.com/dragome/dragome-sdk/blob/master/dragome-form-bindings/src/main/java/com/dragome/forms/bindings/builders/LocalStorage.java

I'll be relocating this to web module.

**Comment by czyzby** [comment]
Preferences implemented, see https://github.com/czyzby/gdx-dragome/tree/master/core/src/com/dragome/gdx/preferences
